List<String> locations = <String>[
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Enugu",
  "Edo",
  "Ekiti",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
  "FCT",
];

List<String> industries = [
    "Food Services",
    "Hospitality",
    "Healthcare",
    "Pharmaceutical",
    "Oil & Gas",
    "Mining",
    "Government",
    "NGO",
    "Non-Profit",
    "International Agencies",
    "Legal",
    "Agriculture",
    "Agro Allied",
    "FMCG",
    "Banking",
    "Financial Services",
    "ICT",
    "Telecommunications",
    "Engineering",
    "Construction",
    "Advertising",
    "Media & Publishing",
    "Manufacturing",
    "Trade",
    "Energy & Power",
    "Art & Design",
    "Automotive & Car Services",
    "Internet & Software",
    "Professional & Social Associations",
    "Religious Bodies & Associations",
    "Waste Management",
    "Real Estate & Property Management",
    "Nutrition, Food & Confectionery",
    "Travels & Tourism",
    "Recruitment & HR Services",
    "Gaming & Sports",
    "Beverages & Drink",
    "fashion & Clothings",
    "Security Agencies",
    "Ecommerce, Retails & Wholesales",
    "Education Services & Research",
    "Consulting",
    "Logistics & Transportation",
    "Aviation & Tours",
    "Others"
  ];

   List<String> jobFunctions = [
    "Accounting, Auditing & Finance",
    "Adminstrative & Office",
    "Agriculture & Farming",
    "Building & Architecture",
    "Community & Social Services",
    "Consulting & Strategy",
    "Creative & Design",
    "Customer Service & Support",
    "Employability & Soft Skills",
    "Engineering",
    "Food Services & Catering",
    "Health & Safety",
    "Hospitality, Leisure & Travel",
    "Human Resources",
    "IT & Software",
    "Legal Services",
    "Management & Business Development",
    "Marketing & Communciations",
    "Medical & Pharmaceutical",
    "Natural Sciences",
    "Other",
    "Project & Product Management",
    "Quality Control & Assurance",
    "Real Estate & Property Management",
    "Research, Teaching & Training",
    "Sales",
    "Security",
    "Supply Chain & Procurement",
    "Trades & Services",
    "Transport & Logistics"
  ];